FROM       intelliops/cronicle:latest
LABEL      maintainer="Sander Bel <sander@intelliops.be>"

RUN        curl https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem -o /usr/local/share/ca-certificates/LetsEncryptX3IdenTrust.crt && \
           chmod 644 /usr/local/share/ca-certificates/LetsEncryptX3IdenTrust.crt && \
           update-ca-certificates
